version: 15
jobs:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: local/vitasdk
    interpreter: !DefaultInterpreter
      commands:
      - '# Each command must succeed'
      - set -e
      - ''
      - '# Variables'
      - root=$(pwd)
      - branch=@branch@
      - commit=@commit_hash@
      - ''
      - '# Configure and build project'
      - mkdir -p build
      - cd build
      - cmake ..
      - make all
      - ''
      - '# Create artifacts'
      - cd $root
      - tar -cf "build-${branch}-${commit:0:8}.tar" -P build *.skprx
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish
    artifacts: build-*.tar
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Cleanup
    runInContainer: true
    image: local/vitasdk
    interpreter: !DefaultInterpreter
      commands:
      - rm -r build
    useTTY: false
    condition: ALWAYS
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
