version: 15
jobs:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: local/vitasdk
    interpreter: !BashInterpreter
      commands:
      - '# Each command must succeed'
      - set -e
      - ''
      - '# Variables'
      - root=$(pwd)
      - branch=@branch@
      - commit=@commit_hash@
      - ''
      - '# Configure and build project'
      - mkdir -p build
      - cd build
      - cmake ..
      - make all
      - ''
      - '# Copy artifacts'
      - mkdir $root/release
      - cp psvshell+.skprx $root/release/
      - ''
      - '# Create release zip'
      - cd $root/release
      - zip $root/release-${branch}.zip *
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish
    artifacts: release-*.zip
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Cleanup
    runInContainer: true
    image: local/vitasdk
    interpreter: !DefaultInterpreter
      commands:
      - rm -r build
      - rm -r release
      - rm release-*.zip
    useTTY: false
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
