#ifndef _BT_H_
#define _BT_H_

typedef enum {
	PSVS_BT_TOUCH_DISABLED = 0,
	PSVS_BT_TOUCH_FRONT_ONLY,
	PSVS_BT_TOUCH_BACK_ONLY,
	PSVS_BT_TOUCH_TOGGLE_F_B,
	PSVS_BT_TOUCH_TOGGLE_D_F_B,
} psvs_bt_touch_t;

typedef enum {
	PSVS_BT_MOTION_DISABLED = 0,
	PSVS_BT_MOTION_NORMAL,
	PSVS_BT_MOTION_NORMAL_INVERTED,
	PSVS_BT_MOTION_VERTICAL,
	PSVS_BT_MOTION_VERTICAL_INVERTED,
} psvs_bt_motion_t;

#endif
